storacha/indexing-service

cmd/main.go, pkg/construct/construct.go, pkg/server/server.go, pkg/service/contentclaims/server.go, pkg/service/contentclaims/server_test.go, pkg/service/contentclaims/service.go, pkg/service/queryresult/queryresult.go, pkg/service/service.go, pkg/types/types.go
Removes repeated `Service` interface from `pkg/server/server.go` and adds to `pkg/types/types.go`. The `Service` defined in `pkg/construct/construct.go` (with lifecycle methods) now extends `types.Service`. Had to move some query structs into `types` to resolve import cycles.
This also now allows the indexing service to be passed as a dependency to the content claims service, and is done here also (although currently unused).
=> refactor: remove repeated `Service` interface from server pkg

cmd/main.go
A couple minor issues when running the service from the CLI:
- a typo in a flag alias
- add default behavior when a private key is not provided
=> fix: issues when running indexing-service from the CLI

pkg/aws/service.go
=> fix: simplify announce address

deploy/app/lambda.tf, deploy/app/legacyclaims.tf
ref #53 
Add the required policies to allow `indexing-service` access legacy resources. Namely:
- `content-claims` DynamoDB table and S3 bucket
- block index table
=> chore: allow access to legacy buckets and tables

pkg/server/server.go
Any error returned from the query engine is a server error - we've already validated the client sent parameters, it's no longer possible for the request to be considered bad.
I also switched magic constant `400` out for `http.StatusBadRequest` for readability.
=> fix: error code on query failure

pkg/construct/construct.go, pkg/service/providerindex/legacy.go
Implementations should return an empty results slice when no results are found, rather than `type.ErrKeyNotFound` error.
=> fix: make no-op legacy claims finder comply with interface expectations

go.mod, go.sum
Upgrade [storacha/go-metadata](https://github.com/storacha/go-metadata) library to get the latest fixes to the schema definition and the marshalling/unmarshalling logic.
=> chore: upgrade storacha/go-metadata library

pkg/internal/testutil/gen.go, pkg/service/providerindex/providerindex.go, pkg/service/providerindex/providerindex_test.go
With the current implementation, we only look in legacy claims storage if IPNI returns no results.
This PR changes this so that we also search in legacy claims when IPNI return results that are not interesting for the current query.
=> fix: fetch from legacy if there are no interesting claims in IPNI

pkg/providerresults/providerresults.go, pkg/providerresults/providerresults_test.go
It is expected for `ProviderResult.Provider.ID` to be empty in location, index and equals claims, as only the `Addrs` field of `peer.AddrInfo` is used in that case.
=> fix: don't break when unmarshalling empty peer.ID

.github/workflows/terraform.yml
We are creating releases automatically whenever a change to `version.json` is pushed. We expected the new tag would trigger our `Terraform` workflow, but it looks like [workflows using `GITHUB_TOKEN` cannot trigger other workflows](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow:~:text=When%20you%20use,push%20events%20occur.).
I want to try using the `workflow_run` event as a potential workaround.
=> feat: deploy to prod automatically on successful releases

deploy/app/gateway.tf
When `terraform.environment` is `prod`, we are creating a cert for the API for `indexer.storacha.network`, but we then set the domain name to `prod.indexer.storacha.network`.
This PR sets the domain name to whatever name was used for the cert.
=> fix: API gateway domain name same as cert

deploy/app/gateway.tf, deploy/app/main.tf, deploy/shared/main.tf
We were creating the API Gateway deployment and stage properly, but missed associating them both, which prevented the API from being available.
=> fix: link the stage with the deployment to make the API available

.github/workflows/release-binaries.yml, .goreleaser.yaml
Upgrade `goreleaser/goreleaser-action` to v6, which will use goreleaser v2, and the Go version being used. Minor adjustments to the config were required according to [the docs](https://goreleaser.com/deprecations/#removed-in-v2).
This should solve the error in the GoReleaser workflow. It complains because the go version line in `go.mod` (which currently reads `go 1.23.2`) shouldn't include the patch number. However, the patch is supported in `go.mod` since Go 1.21.
=> chore: upgrade goreleaser to v2

pkg/aws/bucketfallbackmapp.go, pkg/aws/bucketfallbackmapper.go, pkg/aws/bucketfallbackmapper_test.go, pkg/aws/service.go, pkg/construct/construct.go, pkg/service/contentclaims/identitycidfinder.go, pkg/service/contentclaims/identitycidfinder_test.go, pkg/service/contentclaims/service.go
Return location claims that were never published properly on the blob protocol from ~May - November 2024
fix #63
Essentially this ports https://github.com/storacha/blob-fetcher/pull/14
- When no legacy claims are found in the legacy claims bucket, check if the cid in question has an uploaded blob in carpark (via head request)
- if present, generate a location claim on demand, in much the same way we do for data pre-blob protocol data (reading from the blob-index table)
- however, here we fold into the normal indexing query process, and the way we accomplish this is via identity CIDs. Which is... a bit funky, but seems the simplest mechanism for making everything work together :)
TODO:
- test for bucketFallbackMapper
- maybe integration test the whole thing
=> feat(legacy): add carpark fallback

.github/workflows/deploy.yml, .github/workflows/terraform.yml, README.md, deploy/app/lambda.tf, deploy/app/legacyclaims.tf, deploy/app/main.tf, deploy/app/variables.tf, deploy/shared/main.tf, deploy/shared/variables.tf, pkg/aws/service.go
Resolves #54 
Most of our services get staging and production environments deployed to different regions. This PR enables this separation for the `indexing-service`.
The changes also make the staging `indexing-service` use the staging `content-claims` resources, instead of always pointing to the production ones as it does right now.
=> chore(terraform): deploy staging to a different region

.github/workflows/deploy.yml, .github/workflows/terraform.yml
When I split the terraform workflow in two different workflows to make it reusable in #83 I mistakenly used the same concurrency group for both, which prevents the child workflow from running.
This PR adds the workspace to the concurrency group key so that only workflows that target the same workspace share the same concurrency group.
=> fix(ci): allow terraform jobs to run concurrently when they target different workspaces

Makefile, README.md, deploy/app/.terraform.lock.hcl
- Added `test` target to the Makefile.
- Additional information about `Opentofu` installation for different distros.
- Updated `.terraform.lock.hcl` dependencies due to Linux installation.
- Updated `README.md` about potential failure in the `make init` command.
- Added basic Indexer query command example.
=> chore(main): minor changes & doc enhancements

Makefile, pkg/service/service.go, pkg/service/service_test.go
- Added the Mockery target to the Makefile
resolves https://github.com/storacha/project-tracking/issues/170
=> test(claim-cache): add unit tests for Claim Cache functionality

README.md, docs/infra.md
Add a quick diagram of what a deployment of the service looks like in AWS.
=> feat: add diagram of resources deployed in AWS

Makefile, pkg/service/service.go, pkg/service/service_test.go
- Clean test cache before running tests via `make test`
- Removed invalid mockery config
resolves: https://github.com/storacha/project-tracking/issues/168
=> test(publish-index-claim): add unit tests for Publish Index Claim functionality

Makefile, codecov.yml, pkg/service/service.go, pkg/service/service_test.go
- Added a new target to the makefile to run tests without cache
- Added codecov config to ignore mock files
- Fixed some error messages
Resolves https://github.com/storacha/project-tracking/issues/169
=> chore(publish-equals-claim): add unit tests for Publish Equals Claim functionality

cmd/lambda/getclaim/main.go, cmd/lambda/getclaims/main.go, cmd/lambda/getroot/main.go, cmd/lambda/notifier/main.go, cmd/lambda/postclaims/main.go, cmd/lambda/providercache/main.go, cmd/lambda/remotesync/main.go, cmd/lambda/start.go, deploy/app/lambda.tf, go.mod, go.sum, pkg/aws/bucketfallbackmapper.go, pkg/aws/bucketfallbackmapper_test.go, pkg/aws/service.go, pkg/construct/construct.go, pkg/telemetry/otel.go
Ref: https://github.com/storacha/project-tracking/issues/246
Instrument AWS clients, HTTP clients and redis clients used by the service using existing libraries. Traces look a lot better but still have big gaps. Removing those will require custom instrumentation that will be added in a follow up PR.
Additionally, I refactored lambda startup code to address [Hannah's comment](https://github.com/storacha/indexing-service/pull/96#discussion_r1931203261) in my previous PR.
=> feat: improve instrumentation

deploy/app/dynamodb.tf
Enables deletion protection for production DynamoDB tables so we don't accidentally delete them. Also enables point in time recovery...it might be possible to recreate these tables from the chain data but it will probably be better if we can just restore them.
=> feat: enable point in time recovery and deletion protection in prod

pkg/aws/bucketfallbackmapper.go, pkg/aws/bucketfallbackmapper_test.go
Fixes #103 
The original implementation launched an HTTP server for the test concurrently in a different goroutine. This poses a race condition between starting the server and running the tests. Sometimes, the test was run before the server was ready and the test failed.
Finding the cause has been tricky because, in case of an error in the HEAD request, `BucketFallbackMapper` swallows the original error and returns `ErrKeyNotFound`, masking the real cause of the issue. This error handling has been improved to avoid this.
To fix the test, the regular HTTP server being used has been replaced with an `httptest.Server`. It simplifies the test code as handling its shutdown is easier, but the reason it fixes the issue is that `httptest.Server` prepares the network listener synchronously, and …
=> fix(tests): flaky test in BucketFallbackMapper tests

version.json
closes https://github.com/storacha/project-tracking/issues/306
Update version to v1.2.1 to trigger a new release and a deploy to prod.
=> chore: release v1.2.1

deploy/app/variables.tf, pkg/aws/service.go
`.env.local` template says this is optional and the code (mostly) allows this to be optional.
=> fix: make honeycomb API key optional

Dockerfile
```
1 warning found (use docker --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
Dockerfile:1
--------------------
1 | >>> FROM golang:1.23-bullseye as build
2 |     
3 |     WORKDIR /go/src/indexing-service
--------------------
```
=> chore: resolve docker lint warning

pkg/redis/redisstore.go, pkg/redis/redisstore_test.go
I saw some unexpected traces when debugging some custom instrumentation I'm adding. Basically, the service was not looking for claims in IPNI or legacy systems even though there were no results in the cache.
Turns out that the `SMEMBERS` command doesn't return `(nil)` when the key doesn't exist, as others commands do. Instead, it returns an empty set (see the docs for [SMEMBERS](https://redis.io/docs/latest/commands/smembers/#:~:text=This%20has%20the%20same%20effect%20as%20running%20SINTER%20with%20one%20argument%20key.) and then [SINTER](https://redis.io/docs/latest/commands/sinter/#:~:text=Keys%20that%20do%20not%20exist%20are%20considered%20to%20be%20empty%20sets.)). Therefore, the store was returning an empty slice instead of `ErrKeyNotFound`.
I added an explicit existence check in …
=> fix: handle non-existent keys properly in Store.SMembers

deploy/app/legacyclaims.tf
If your AWS deployment region is set to `us-west-2` for example, then your deployment will fail because the staging claims bucket is actually in `us-east-2`.
=> fix: region for legacy claims bucket

pkg/blobindex/shardeddagindex.go
JS blob index (the ones we create on the client) encodes the root block as the first block in the CAR not the last.
This PR restores parity with the JS blob index, allowing indexes created using Go to serialize to the same bytes as indexes created by JS and by virtue hash to the same CID:
BEFORE:
AFTER:
=> fix: blob index compatibility

pkg/service/providerindex/providerindex.go, pkg/service/providerindex/providerindex_test.go
If one or multiple users upload the same blob multiple times the `assert/index` invocation will create an advert that already exists. This will cause `ipni-publisher` to return `ErrAlreadyAdvertised` and the invocation fails. This PR ignores `ErrAlreadyAdvertised` because, that's fine, whatever.
It also adds a mutex around publish per https://github.com/storacha/ipni-publisher/issues/3
=> fix: allow skipping publish of existing advert

pkg/construct/construct.go
Traces in prod show queries taking around 9 secs to complete. It is clear from taking a look at the spans that the concurrency level is being hit and an increase could improve query time.
I'm bumping it to 15 for now to test how it goes. We might want to choose an even higher number. Concurrency is based in goroutines, which are very efficient, so it should be possible to go much higher. The limiting factor would probably be networking.
=> feat: increase concurrency

pkg/service/providerindex/providerindex.go, pkg/service/providerindex/providerindex_test.go
via 656fa6769c5dad56e2a99590930f09dd2f324e1b
- ProviderIndexService.getProviderResults now queries IPNI and legacy claims concurrently using channels. If IPNI returns a valid result, the legacy lookup is canceled.
- errors from both queries are joined to provide better context when neither returns data.
- tests have been updated to cover these new scenarios.
- closes #120 
via ae21e4484301fc1f3f8f869f256e52d9e27ae560 
- adds a few more events to the span for the operation be modified allowing timing of various operations to be inferred. If we prefer this change be landed separately (or not at all!) happy to revert it.
=> feat(provider-index): parallelize claim lookups

pkg/aws/bucketfallbackmapper.go, pkg/service/contentclaims/simplefinder.go
Thinking specifically of enabling cancellation of the request by cancelling the provided context.
`BucketFallbackMapper` is used by the legacy claims logic, and now that #122 will make that run in parallel with the query to IPNI and can potentially be cancelled, I took a look at the context propagation chain and noticed we were not using it in these calls.
=> fix: use the provided context in HTTP requests

.env.local, deploy/app/lambda.tf, deploy/app/variables.tf
Enable setting the carpark to use for the LEGACY_DATA_BUCKET_URL. This simply completes the set of vars needed to fully complete custom configuration of legacy lookups
Useful for local testing downstream services like Freeway against prod data, but without using the prod service
- add a var for legacy data bucket url
- use legacy data bucket url when configured
=> Override data bucket url

deploy/app/lambda.tf, pkg/aws/service.go, pkg/construct/construct.go, pkg/redis/contentclaimsstore.go, pkg/redis/providerstore.go, pkg/redis/redisstore.go, pkg/redis/shareddagindexstore.go
Currently, our cache hit rate for some of our redis instances is really low, because it turns out 1 hour really isn't long enough to hold some of this data. There's not reason not to hold it longer -- we've allocated almost 10GB to these redis instances and we're currently using all of a couple MB.
- Enable passing a specific expiration parameter to each redis store
- Pipe all the way out to an AWS env var
- Up expirations times to:
- 1 month on prod, 1 week on staging for providers (very small data)
- 1 week on prod, 1 day on staging for claims
- 1 day on prod, 1 hour on staging for indexes (larger data)
=> feat(redis): enable tuning of caching parameters

version.json
=> chore(version): update for release

cmd/lambda/start.go
I confirmed with some experimentation that deferring the call doesn't work. The`lambda.Start` call never returns.
=> fix: ensure shutdown functions are called when lambdas are destroyed

pkg/telemetry/otel.go
fixes #134 
Context propagation was not properly configured and incoming trace context was not being extracted from requests coming from the gateway.
Interestingly, telemetry was already configured to sample only requests that were sampled in the upstream service, but since context propagation was not working the result was that all requests were being sampled. Fixing context propagation also means that the indexer will only sample requests that are sampled in the gateway.
=> fix: distributed tracing not working

version.json
Releasing v1.6.0 to deploy the fix to distributed tracing, caching claims generated from the blob index table and the go-ucanto fixes.
Currently telemetry is disabled in prod and merging this will re-enable it. I'll keep an eye on honeycomb to confirm the fix is working and the indexer is sampling only the traces that are sampled in the gateway.
=> chore(release): v1.6.0

pkg/service/providerindex/legacy.go, pkg/service/providerindex/legacy_test.go
Fixes the empty peer ID which should allow the indexer to process records in the queue.
> deserializing message: failed to parse peer ID: invalid cid: cid too short
> https://github.com/storacha/indexing-service/blob/04ac62a233322607e72eb592c11d9b59d742bef8/pkg/aws/sqscachingqueue.go#L120
The hard coded peer ID is actually the peer ID of the storage node we'll be deploying to production shortly.
=> fix: peer ID in legacy synthesized provider result

deploy/app/lambda.tf
Has been observed to take >30s - increase to 5 minutes.
=> chore: increase providercache lambda timeout

cmd/lambda/providercache/main.go, pkg/service/providercacher/simpleprovidercacher.go, pkg/service/providercacher/simpleprovidercacher_test.go
1. Prioritize caching the DAG root.
- This is oftentimes the multihash that'll be queried to obtain the index.
2. Do not hold up the queue on lambda timeout.
- This is probably a massive DAG that'll exceed lambda timeout. Retrying will cost more writes, probably still not succeed and hold up the fifo queue.
This also adds a graceful shutdown period - [context is canceled before the lambda times out](https://medium.com/@filiplubniewski/how-to-leverage-aws-lambda-timeouts-with-go-context-cancellation-7dacde656540). This allows the cache provider lambda to inspect the error and succeed anyway.
=> perf: discard caching jobs that will timeout

cmd/lambda/providercache/main.go
Return the failed items on error so that the successful items are not retried.
=> fix: report failures so successfully cached provider info is not retried

deploy/app/lambda.tf
I read about how to do this on stackoverflow but I missed the bit about configuring the event source mapping. 🤦 sorry.
> To activate partial batch reporting
> [...]
> Run the following command to activate `ReportBatchItemFailures` for your function.
https://docs.aws.amazon.com/lambda/latest/dg/services-sqs-errorhandling.html#services-sqs-batchfailurereporting
=> fix: enable batch item failure reporting

cmd/lambda/providercache/main.go
🤷‍♂️ I wondered if this was necessary...looks as though it is.
> Update your function code to catch all exceptions
https://docs.aws.amazon.com/lambda/latest/dg/services-sqs-errorhandling.html#services-sqs-batchfailurereporting
=> fix: do not return error for item failures

deploy/app/sqs.tf
We increased the providercache lambda timeout to 300s but didn't update the visibility timeout in the SQS queue it is consuming messages from. That makes the message in the batch being processed available to other lambdas before the one processing them has the chance to delete them and/or mark them as processed.
=> fix(sqs): adjust visibility timeout to lambda timeout

pkg/service/providercacher/simpleprovidercacher.go, pkg/service/providercacher/simpleprovidercacher_test.go
This PR alters the provider cacher code to concurrently cache provider records up to 5 at a time.
In manual testing with an atrificial network delay I was able to see caching 10k provider records reduce from 20s to around 5s.
The aim is to process the caching queue faster as it is continually growing atm.
=> perf: concurrent provider cache

.github/workflows/deploy.yml
We currently only run plans of our terraform config for staging. Our config for prod is slightly different from that of staging, and today we only catch issues when we apply the config to prod as part of a release.
This PR updates our CI so that plans are run for prod. That way we can anticipate and fix issues when updating the config before they get merged.
=> fix(ci): run tofu plans for prod when not releasing

deploy/app/cloudfront.tf, deploy/app/gateway.tf
For prod, we want the main `indexer.storacha.network` domain to point to the cloudfront distribution. The current config uses that domain name both as a custom domain for API gateway and as an alternate domain for the cloudfront distribution.
Instead of that, we will give the API gateway its own `api.indexer.storacha.network` domain to make it clearer which resource is using which domain name. This allows removing references to the gateway's custom domain in cloudfront route53 records, and references to the cloudfront domain in the gateway's config.
=> chore(dns): alternate domain for API gateway, main domain for cloudfront

tools/metadata/parse.go
Adds a debugging script that parses known metadata (as found in a JSON response from the IPNI HTTP API) and prints it to the console.
e.g. parsing the metadatas found in response from https://cid.contact/multihash/QmTw7zKmh4xrrverrsg5zMTXVdti5wrPSL8wxCdKR2sL2w :
=> feat: add metadata parse and print tool

cmd/lambda/providercache/main.go, deploy/app/s3.tf, pkg/aws/sqscachingqueue.go
resolves https://github.com/storacha/indexing-service/issues/160
* Lifecycle rule removes indexes from bucket after 2 weeks.
* Should be faster (do not have to wait for delete operation).
* Should be cheaper (zero delete requests - and lifecycle rules are not charged).
=> feat: expire caching queue indexes

cmd/lambda/start.go, deploy/app/lambda.tf, pkg/aws/service.go, pkg/telemetry/otel.go
We're once again overconsuming our capacity on Honeycomb, cause while we're limiting spans to those with a parent on API calls, now that the provider caching job is working, we're recording tons of child span interactions with redis
for spans that have no parent, introduce a sampling ratio, to prevent overloading honeycomb.
=> fix(telemetry): introduce sample ratio

deploy/app/sqs.tf
Get the caching queue running faster
Convert the SQS queue to be non-FIFO.
There's no need for it to be -- the operation is idempotent
=> feat(deploy): use non fifo sqs queue

pkg/aws/sqscachingqueue.go
Apparently setting a MessageGroupID is not allowed on a non-FIFO queue, which is causing event delivery to fail
- Remove MessageGroupID
=> fix(aws): fix caching queue for non-fifo

Makefile, pkg/blobindex/datamodel/shardeddagindex.go, pkg/blobindex/datamodel/shardeddagindex_cbor_gen.go, scripts/cbor_gen.go
Support realistically size blob indexes by increasing cbor-gen's max slice length
Needed to create a manual script for cbor-gen to pass a custom array size unfortunately.
Set to 131072 for now
=> fix(cbor-gen): use larger value for arrays in blobindex

go.mod, pkg/service/providerindex/providerindex.go, pkg/service/providerindex/providerindex_test.go
We're getting a number of 500s when IPNI hangs indefinitely, eventually causing lambdas to timeout.
when IPNI queries hang (which happens frequently), don't get stuck till lambda timesout -- limit wait to 1.5 seconds
- add timeout to context before querying with IPNI
- inject clock library for time testing (this is temporary till synctest lands in default golang build -- it's in 1.24 but not default build)
- add test to verify behavior
=> feat(providerindex): don't hang on IPNI timeout

pkg/service/providerindex/providerindex.go
re: https://github.com/storacha/indexing-service/pull/200#pullrequestreview-2822538569
Goroutines are cheap, let see if simply increasing job concurrency will be fast enough.
=> fix: increase cache queue concurrency

Makefile, cmd/lambda/getdiddocument/main.go, deploy/app/lambda.tf, pkg/server/server.go, pkg/server/server_test.go
Serve a DID document like the following at `/.well-known/did.json`. It allows external entities to resolve and verify our `did:web`:
```json
{
"@context": "https://w3id.org/did/v1",
"id": "did:web:indexer.storacha.network",
"verificationMethod": [
{
"id": "did:web:indexer.storacha.network#owner",
"type": "Ed25519VerificationKey2020",
"controller": "did:web:indexer.storacha.network",
"publicKeyMultibase": "z6MknTPdpBGfFysJWCJn7SbhrAA7Xmp6ZCnjH9dPxJy2T7sk"
}
],
"assertionMethod": [
"did:web:indexer.storacha.network#owner"
],
"authentication": [
"did:web:indexer.storacha.network#owner"
]
}
```
=> feat: add `GET /.well-known/did.json` route

deploy/app/lambda.tf, deploy/app/legacyclaims.tf, pkg/aws/bucketfallbackmapper.go, pkg/aws/bucketfallbackmapper_test.go, pkg/aws/dynamoallocationstable.go, pkg/aws/dynamoallocationstable_test.go, pkg/aws/service.go, pkg/service/providerindex/providerindex.go, pkg/service/providerindex/providerindex_test.go
Fix our caching issues with IPNI and store protocol
- the basic approach here is to have the no-providers cache ONLY apply to IPNI queries
- changes are in ProviderIndex moving no-providers reads+write to inside the IPNI query
- this neccesitates one additional optimization:
- the slow step child for legacy queries is the fallback mapper, which actually does a head request on an R2 bucket
- the optimization introduced is to check the allocations db table first -- if it's not there, no need for a potential cross region request to R2
Changes to the indexer are.... tricky. We may need to figure out a long term solution here to get to more rapidly deployable solutions & potentially blue/green deployments
=> feat(providerindex): use no-providers with IPNI only

pkg/service/service.go
The context ID when publishing an equals claim needs to be the content hash not the equals hash.
This is because if we query for the equals hash we try to get a location claim for the content:
https://github.com/storacha/indexing-service/blob/ebd51266fdfbfcb230d5620dca81634a070558cc/pkg/service/service.go#L185-L191
When querying the indexer for a piece CID `bafkzcibdr4dqnpio7ck6dniyyslw22qkhkoxzzy7v52plrotzibt2hwvdeya6uaw` an equals claim is expected to be returned, giving us the shard CID.
Currently, we are casting a binary CID as a multihash and using that to query IPNI, which is failing with the error:
```console
ERROR    indexer/find    find/server.go:189    find: input is not a valid base58 or hex encoded multihash    
{
"multihash": …
```
=> fix: equals claim content lookup

pkg/service/providerindex/legacy.go, pkg/service/providerindex/legacy_test.go
While debugging the indexing service cache I found this error. I'm not 100% certain I understand what this field is for in the metadata but it is not for the DAG root CID.
=> fix: content CID is not a shard CID

deploy/app/lambda.tf, deploy/app/legacyclaims.tf, pkg/aws/blockindextablemapper.go, pkg/aws/blockindextablemapper_test.go, pkg/aws/dynamomigratedshardchecker.go, pkg/aws/dynamomigratedshardchecker_test.go, pkg/aws/service.go
implements blocking of retrievals by skipping old web3.storage cids that are not listed in the store table or the blob-registry table per #213 
- in block index table mapper
- skip shards if they are dot storage shards and are not listed as migrated
- implement migrated shard checker
- checks both store table and blob registry table to see if a shard is migrated
- update deploy configs
Before we ship this, I really need to test round trip by deploying an indexer env connected to prod
=> feat(aws): skip unmigrated dotstorage shards

pkg/server/server.go, version.json
It looks like piri sends claims as `POST /` instead of `POST /claims`. Let's allow it while it gets fixed.
=> fix: allow publishing claims by POSTing to `/` too

pkg/aws/dynamomigratedshardchecker.go, pkg/aws/dynamomigratedshardchecker_test.go, pkg/aws/service.go
We were interchanging the table names when creating the migrated shard checker, which caused queries to fail.
=> fix: migrated shard checker was getting mixed table names
